name: global
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none
environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  dio: ^5.3.3
  logger: ^2.0.2+1
  flutter_screenutil: ^5.7.0
  go_router: ^12.0.0
  google_fonts: ^5.1.0
  image_picker: ^1.1.2
  image_cropper: ^5.0.1
  flutter_svg: 
  file_picker: ^6.1.1
  gap: ^3.0.1 
  smooth_page_indicator: ^1.0.0+2
  cached_network_image: ^3.2.3
  hasura_connect: ^5.0.0+3
  shared_preferences: ^2.2.2
  pinput: ^4.0.0
  path_provider: ^2.1.3
  flutter_card_swiper: ^7.0.0
  expandable: ^5.0.1
  
  permission_handler: ^11.3.1
  flutter_typeahead: ^4.0.0
  intl: ^0.17.0
  sqflite: 
  
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:


